### ISSUE TITLE
RF Output Level on CW Mode

### ISSUE THREAD

**Issue by Koichi-Koyama** [pavel-demin/stemlab-sdr-notes#12]
Dear Pavel-san, 
 
This is Koichi Koyama (Mr) from Japan, and I have been using  “OpenHPSDR mRX PS v3.4.9” for my new Red Pitaya SDR (16). 
OpenHPSDR is very nice software and thank you for your efforts for the development. 
 
After replacement of STEMLab125-14 with the new STEMLab122-88-16 SDR in my homebrew 200W HF transceiver, I have noticed that the output level of single carrier by CW key-down is increased by approx. 3dB or more from “Tune” mode.   
In case of STEMLab125-14, the output level of single carrier is same between CW key-down and clicking “Tune”. 
This is serious issue for me as it causes shutdown or breakdown of my linear amplifier due to excessing driving power.  

I have asked Red Pitaya technical staff who has advised me to contact you or open the issue in this forum, as it seems it is related to OpenHPSDR software. 

I would be grateful if you could advise me if this issue can be solved or any solution for me to take, other than changing driving level manually. 

Kind regards,

Koichi Koyama
7N1ICA

**Comment by pavel-demin** [comment]
Thank you for testing the CW mode. I think that this problem should be fixed in the code with [this commit](https://github.com/pavel-demin/stemlab-sdr-notes/commit/c8d18d25c0b28e5d2a62a333741952631a662f46#diff-5f93faa912cb2f7a72e55d1e6dd8113e). The fixed code will be in the next release. Meanwhile, could you please check if [this prerelease version](https://www.dropbox.com/sh/a1yecde4hs91ji0/AABkdF8vSaSMIdzSCE5wk2oqa/stemlab-sdr-alpine-3.9-armv7-20190414.zip?dl=1) works better for you?

**Comment by Koichi-Koyama** [comment]
Dear Pavel-san,

 

Thank you for very much your response. 

 

As far as I have checked the prerelease version, the RF output level on CW
mode has been fixed which is the same level of Tune mode. 

Do you have any idea when the new issue will be released?

 

Thank you again for your support.

 

Best regards,

 

Koichi Koyama

7N1ICA

**Comment by pavel-demin** [comment]
The fixed code is now in the latest release. Closing this issue.

**Comment by Koichi-Koyama** [comment]
Thank you for the information and well noted. 

Koichi Koyama
7N1ICA

----- 元のメッセージ -----
From: "Pavel Demin" <notifications@github.com>
宛先: "pavel-demin/stemlab-sdr-notes" <stemlab-sdr-notes@noreply.github.com>
Cc: "Koichi-Koyama" <masuya.udon@drive.ocn.ne.jp>, "Author" <author@noreply.github.com>
送信済み: 2019年10月26日 午前 3:48
件名: Re: [pavel-demin/stemlab-sdr-notes] RF Output Level on CW Mode (#12)

> The fixed code is now in the latest release. Closing this issue.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
