### ISSUE TITLE
Transceiver compatible with HPDR - Third RX (RX3) available for something else than pre-distorsion?

### ISSUE THREAD

**Issue by satfan52** [pavel-demin/stemlab-sdr-notes#21]
Hello Pavel,

I don't use pre-distorsion so I was wondering if by changing a parameter and if needed by recompiling the third RX (RX-3) could be used to receive an additional band (so 3 totally independent Receivers instead of 2 as it is at the moment since the third one is used for pre-distorsion). 

Thanks 
Regards
Peter

**Comment by pavel-demin** [comment]
The frequency mixers of RX3 and RX4 are connected to the TX DDS. So they are always tuned to the TX frequency. There is no parameter to change this connection.
